### ISSUE TITLE
npm and yarn start failed

### ISSUE THREAD

**Issue by camtonguyen** [yussan/grunt-pug-sass-boilerplate#18]
Hi @yussan , I ran this project and got this issue:
<img width="725" alt="Screen Shot 2019-10-14 at 2 09 38 PM" src="https://user-images.githubusercontent.com/21218195/66734194-59be8100-ee8c-11e9-8cbe-492cc2084c62.png">
Could you plz help to check it? 
Thanks!

**Comment by yussan** [comment]
thanks for issue, checking....

**Comment by yussan** [comment]
Cause of error : 
>> Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (72)
>> For more information on which environments are supported please see: https://github.com/sass/node-sass/releases/tag/v4.5.3

Solution : 
- update node-sass
- only use npm install and npm start (README.md updated)


Status : solved and merged
