### ISSUE TITLE
change grunt config to css and html result in /dist

### ISSUE THREAD

**Issue by yussan** [yussan/grunt-pug-sass-boilerplate#3]
- [x] minify css, `dist/css/*.css`
- [x] unminify html, `dist/*.html`

**Comment by yussan** [comment]
thanks @sagarvd01 to contribute in first cssmin issue

**Comment by sagarvd01** [comment]
html minifying is easy but in case of unminifying, I can't get it working. I'll try again.

**Comment by yussan** [comment]
by default grunt-contrib-pug save html unminfy, we want to unminfy html to easy for read by human

**Comment by Skipvanthof** [comment]
I think i have found a fix for this, can i create a pull request?

**Comment by yussan** [comment]
@Skipvanthof thanks is merged now
